import { CategoryGamesContent } from "./CategoryGamesTypes";

export const defaultCategoryGamesContent: CategoryGamesContent = {
  sectionTitle: "Upcoming Tournaments",
  sectionDescription: "Play our most popular games and win big",
  categories: ["Popular", "New", "Tournaments", "Action", "Puzzle"],
  games: [
    {
      id: 1,
      title: "Ludo King",
      category: "Board",
      image: "https://img.icons8.com/fluency/96/dice.png",
      players: "2,645 playing",
      prize: 5000,
      hot: true,
      tags: ["popular", "board", "tournaments"],
    },
    {
      id: 2,
      title: "Rummy Classic",
      category: "Card",
      image: "https://img.icons8.com/fluency/96/clubs.png",
      players: "1,854 playing",
      prize: 10000,
      hot: true,
      tags: ["popular", "card"],
    },
    {
      id: 3,
      title: "Fantasy Cricket",
      category: "Sports",
      image: "https://img.icons8.com/fluency/96/cricket-ball.png",
      players: "5,326 playing",
      prize: 25000,
      hot: false,
      tags: ["popular", "sports", "tournaments"],
    },
    {
      id: 4,
      title: "Car Race 3D",
      category: "Racing",
      image: "https://img.icons8.com/fluency/96/car.png",
      players: "942 playing",
      prize: 2000,
      hot: false,
      tags: ["racing", "action"],
    },
    {
      id: 5,
      title: "Carrom Disc",
      category: "Board",
      image: "https://img.icons8.com/fluency/96/poolside.png",
      players: "1,232 playing",
      prize: 3000,
      hot: false,
      tags: ["board", "new"],
    },
    {
      id: 6,
      title: "Bubble Shooter",
      category: "Arcade",
      image: "https://img.icons8.com/fluency/96/football2.png",
      players: "856 playing",
      prize: 1500,
      hot: false,
      tags: ["arcade", "puzzle"],
    },
    {
      id: 7,
      title: "Poker Nights",
      category: "Card",
      image: "https://img.icons8.com/fluency/96/diamonds.png",
      players: "3,421 playing",
      prize: 15000,
      hot: true,
      tags: ["popular", "card", "tournaments"],
    },
    {
      id: 8,
      title: "8 Ball Pool",
      category: "Sports",
      image: "https://img.icons8.com/fluency/96/billiard-ball.png",
      players: "2,150 playing",
      prize: 7500,
      hot: false,
      tags: ["sports", "popular"],
    },
  ],
  viewAllButtonText: "View All tournaments",
  active: true,
};
